#Hugo configuration
title = "asdf"
baseURL = "https:\/\/asdfasfd.asdf.asdf"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "asdf.asdf"
